### ISSUE TITLE
Settings for "api_key" input's placeholder

### ISSUE THREAD

**Issue by SofiaSousa** [ruby-grape/grape-swagger-rails#113]
Is there any chance to add a configuration option to make possible for "api_key" input's placeholder to be customized?

https://github.com/ruby-grape/grape-swagger-rails/blob/5799fa26736e02d9b5fc040c12b5b883c6c46ea9/app/views/grape_swagger_rails/application/index.html.erb#L99

In our case, we are using Authorization bearer and it would be more intuitive for the end user to see the "access_token" placeholder instead of "api_key".

**Comment by dblock** [comment]
It's a good idea, care to contribute?

**Comment by dblock** [comment]
Closed via https://github.com/ruby-grape/grape-swagger-rails/pull/114
