### ISSUE TITLE
when rails an exception with http://localhost:3000/swagger, can not reload again, restart rails server will works

### ISSUE THREAD

**Issue by TangMonk** [ruby-grape/grape-swagger-rails#12]

**Comment by whatasunnyday** [comment]
I think this has something to do with rails engines and reloading config/routes.rb. I have the same problem with my mounted Grape API without Swagger.

**Comment by dblock** [comment]
@TangMonk @whatasunnyday Can you help me understand the problem? Is it "Rails reloading doesn't reload `GrapeSwaggerRails` configuration?

**Comment by wonderer007** [comment]
I also wanted to know what exactly this error is Please explain ......

**Comment by whatasunnyday** [comment]
I've actually fixed the problem for myself. I think it only occurs if you have the wrong auto loading directory. Suppose you've file path looks something like this:: `/app/models/api_engine/api.rb`

My original `config/application.rb` looked like this:
```ruby
    config.paths.add File.join('app', 'api_engine'), glob: File.join('**', '*.rb')
    config.autoload_paths += Dir[Rails.root.join('app', 'api_engine')]
```

This fixed it:
```ruby
    config.paths.add File.join('app', 'api_engine'), glob: File.join('**', '*.rb')
    config.autoload_paths += Dir[Rails.root.join('app', 'api_engine', '*')]
```

**Comment by dblock** [comment]
Thanks @whatasunnyday this would make sense.

@TangMonk @wonderer007 care to try this in your projects?

**Comment by wonderer007** [comment]
@whatasunnyday its not working for me   

config.paths.add File.join('app', 'api_engine'), glob: File.join('**', '*.rb')
config.autoload_paths += Dir[Rails.root.join('app', 'api_engine', '*')]  

still same error

**Comment by whatasunnyday** [comment]
@wonderer007 What is the name of the directory that your api lives in? It only makes sense to use api_engine if you have a folder called api_engine in apps.

**Comment by aschuster3** [comment]
Seeing as the original poster hasn't responded in quite a while, I'm going to assume a solution was found.  If one was not, ping me here and I'll open this issue again or feel free to just open a new issue.
