### ISSUE TITLE
Use "request" data for default app_url

### ISSUE THREAD

**Issue by brodock** [ruby-grape/grape-swagger-rails#17]
Is it possible to use "request" data to generate a default app_url that is always relative to the host where it was accessed from?

While we don't use it in a multi tenancy application (which would be a valid use case for that), our current development environment have some host variations that cannot be easily (in a clear way) bypassed.

**Comment by dblock** [comment]
This is a good feature request, it means allowing the `app_url` configuration setting to be a block that takes the request. Probably not very hard to build, would love a pull request.

**Comment by polarlights** [comment]
Add the code below to `config/initializers/swagger.rb`:

``` ruby
GrapeSwaggerRails.options.before_filter_proc = lambda { GrapeSwaggerRails.options.app_url = request.protocol + request.host_with_port }
```

**Comment by dblock** [comment]
@polarlights This works? Can we document it in README? (PR please)

**Comment by polarlights** [comment]
well. It should be a proc. I have push a new PR now. Please check.

**Comment by dblock** [comment]
Documented in https://github.com/ruby-grape/grape-swagger-rails/commit/b51bf27e483a6483a9b0ba44c53279504308e235.
