### ISSUE TITLE
Detach Fork

### ISSUE THREAD

**Issue by whatasunnyday** [ruby-grape/grape-swagger-rails#26]
This is a very minor issue.

Would ruby-grape considering detaching the fork from BrandyMint? It's a very minor ux issue because its constantly comparing the master of the two repos. I'm very grateful for BrandyMint's contributions and would support adding the original repo to the README.

> To detach the fork and turn it into a standalone repository on GitHub, contact GitHub support.

https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/
https://github.com/contact

**Comment by dblock** [comment]
I've emailed the owners of that repo and asked them to destroy it. If I don't hear from them in a few days I'll do this.

**Comment by dblock** [comment]
cc: @anaumov, @bespalawn, @dapi ...

**Comment by dblock** [comment]
The parent fork was destroyed but Github found a new parent. I've contacted support to detach the fork.

**Comment by dblock** [comment]
GitHub took care of it. Onward!
