### ISSUE TITLE
markdown generated style ugly for Table Of Content(TOC)

### ISSUE THREAD

**Issue by TangMonk** [ruby-grape/grape-swagger-rails#28]
the `<li>` and `table of content` without no Indentation

**Comment by dblock** [comment]
Could you add a screenshot? Is this a problem with grape-swagger-rails or a style in swagger-ui?

**Comment by TangMonk** [comment]
Thanks for your reply.

That's not a bug, that's stylesheets problem

I have a markdown note with following:

```markdown
* TOC
{:toc}

# title 1

## title 1 - content 1

# title 2

## title 2 - content 1
```

I desired the output like this(Table Of Contents with Indentation):

![image](https://cloud.githubusercontent.com/assets/3498786/9536841/69972cae-4d63-11e5-9ea6-c61488fc7875.png)
 
But actually output (Table Of Contents with no Indentation): 

![image](https://cloud.githubusercontent.com/assets/3498786/9536846/982f5122-4d63-11e5-82bb-cf5e2347cccf.png)

**Comment by dblock** [comment]
It's a stylesheet bug :)

**Comment by dblock** [comment]
This was fixed.
