### ISSUE TITLE
Problem with file uploading at 0.1.1 version

### ISSUE THREAD

**Issue by ivan-garanin** [ruby-grape/grape-swagger-rails#35]
I have got issue with uploading files at 0.1.1 version of grape-swagger-rails
This is screenshot of swagger with grape-swagger-rails version 0.1.1
![2015-10-12 13 49 31](https://cloud.githubusercontent.com/assets/5081342/10425495/c4db6cc4-70e0-11e5-8bac-fbe1f6d3d089.png)
This errors comes after sending request: 
![2015-10-12 13 50 19](https://cloud.githubusercontent.com/assets/5081342/10425529/fc1fecfa-70e0-11e5-944e-f41f594c63e3.png)
<img width="1059" alt="2015-10-12 13 50 45" src="https://cloud.githubusercontent.com/assets/5081342/10425528/fc1df0da-70e0-11e5-9f53-38274a6644fb.png">

And this is with 0.1.0
![2015-10-12 13 51 38](https://cloud.githubusercontent.com/assets/5081342/10425518/e21c84d0-70e0-11e5-9712-708b785998b5.png)

**Comment by dblock** [comment]
This probably has something to do with content-type, but I would first try to get a `curl` version of this error so we can figure out whether this is a UI bug in Swagger or a server bug in your grape API (and possibly in grape itself).

**Comment by calfzhou** [comment]
the same problem. And all custom param types became `undefined`.

**Comment by calfzhou** [comment]
v0.1.0 sends this request payload:
```
------WebKitFormBoundaryFemTvyBHziujgz88
Content-Disposition: form-data; name="portrait"; filename="Encodings.png"
Content-Type: image/png


------WebKitFormBoundaryFemTvyBHziujgz88--
```

but v0.1.1 sends
```
------WebKitFormBoundaryk7VAynaT8ElkTpVv--
```

**Comment by calfzhou** [comment]
Solved by setting param type to `form`,
```ruby
requires :portrait, type: Rack::Multipart::UploadedFile, documentation: { param_type: 'form' }
```

![image](https://cloud.githubusercontent.com/assets/3761553/10533311/f6025a3a-73f9-11e5-8995-bfa90d115253.png)

**Comment by dblock** [comment]
Do we need to document this?

**Comment by unloved** [comment]
yes

**Comment by aschuster3** [comment]
This appears to be an issue with the `grape-swagger` dependency on version 0.1.1 of this gem.  I didn't find any evidence of it being documented here or on `grape-swagger`, but there have also been a number of version bumps since October 2015.

I'm going to go ahead and close this issue.  If it is still a problem, I'll reopen this issue or feel free to create a new one.
