### ISSUE TITLE
current_user is undefined in before filter

### ISSUE THREAD

**Issue by olegsokolov513** [ruby-grape/grape-swagger-rails#38]
Hi, thanks for your nice work.
I am going to implement Authentication and Authorization for my Swagger UI.
After checking the documentation, I decided to use current_user inside GrapeSwaggerRails.options.before_filter.
Unfortunately it says current_user is undefined.
I am currently using clearance gem for authentication.

Regards
Oleg

**Comment by dblock** [comment]
I am not sure how it's done with clearance, find out where and how it defines `current_user` and it's possible you'll have to mixin something on re-define a method. With warden for example you have to do `ENV['warden'].current_user` or something like that.

**Comment by olegsokolov513** [comment]
Thanks for your reply, @dblock 
Here is the solution.
For clearance, request.env[:clearance].current_user works.
