### ISSUE TITLE
Update rubygems version?

### ISSUE THREAD

**Issue by aliuk2012** [ruby-grape/grape-swagger-rails#43]
It looks like this project is still being actively developed. Any chance of updating rubygems?

**Comment by dblock** [comment]
Wow it has been a year! Release 0.2.0, https://twitter.com/grapeframework/status/702164754425585664.

**Comment by aliuk2012** [comment]
Thank you for the quick response :+1:

**Comment by dmitry** [comment]
No release 0.2.1 in https://github.com/ruby-grape/grape-swagger-rails/releases

**Comment by aschuster3** [comment]
@dmitry Thanks for the heads up, should be up now
