### ISSUE TITLE
Help with configuration

### ISSUE THREAD

**Issue by zeroedin** [ruby-grape/grape-swagger-rails#45]
Running into trouble with configuration for my rails app.  I'm using the following versions 
```Ruby
#Gemfile.lock
grape (0.14.0)
grape-swagger (0.10.4)
grape-swagger-rails (0.2.0)
```

I have the following initializer:

```Ruby
#config/initializer/swagger.rb
GrapeSwaggerRails.options.before_filter_proc = proc {
  GrapeSwaggerRails.options.app_url = request.protocol + request.host_with_port
}
GrapeSwaggerRails.options.url = '/api/v1/swagger_doc.json'
```

And I have the following API class:

```Ruby
#app/api/api.rb
require 'grape-swagger'

class API < Grape::API
  prefix 'api'
  version 'v1', using: :path

  mount People::List
  mount Person::Single

  add_swagger_documentation 
end
```

The following routes:
```Ruby
#config/routes.rb
mount API => '/'
mount GrapeSwaggerRails::Engine => '/api-docs'
```

When I visit `/api-docs` everything appears to start to load correctly but the AJAX calls being made by `swagger-ui.js` are hitting urls formatted like this: `http://somedomain/api/v1/swagger_doc.json/people.json`

I have no idea now what is causing `/swagger_doc.json` to be dropped inside of the request urls?

I feel like I am missing something fundamental but I haven't been able to figure it out.  Any information that might be helpful would be appreciated. 

Thanks

**Comment by zeroedin** [comment]
Ok so I took a closer look at the `/spec/dummy` in this repository and made some changes:

```
#config/initializer/swagger.rb
GrapeSwaggerRails.options.before_filter_proc = proc {
  GrapeSwaggerRails.options.app_url = request.protocol + request.host_with_port
}
GrapeSwaggerRails.options.url = '/api/v1/swagger_doc'
```
```
#app/api/api.rb
class API < Grape::API
  prefix 'api/v1'
  # version 'v1, using: :path'

  mount V1::People::List
  mount V1::Person::Single

  add_swagger_documentation
end
```

I also added `namespace` and `desc` to my API methods which I was missing.  

I now get the basically functionality working.  However I'm not sure my handling of the versioning now using `prefix` is correct in `app/api/api.rb`

Again any extra info would be helpful.

**Comment by dblock** [comment]
That `/api/0.1/person` is that something Swagger constructs? Or is it actually where your API is mounted?

I think you want `prefix :api` and `version :v1, using: :path` (there's something weird in your quotes there :)

**Comment by dblock** [comment]
@zeroedin were you able to resolve this?

**Comment by aschuster3** [comment]
For anybody else visiting this issue, I think the root of this problems lies with the default settings for `add_swagger_documentation` which can be gleaned from [here on the `grape-swagger` repository](https://github.com/ruby-grape/grape-swagger/blob/eb1f283c6e8e8e20d71a3083b8d96c19e70e42c7/lib/grape-swagger/doc_methods.rb#L90).  Be sure to cross reference those defaults with the version of `grape-swagger` that you are using.

I'm going to go ahead and close this issue.  If it was not resolved, ping me here or feel free to open another one.
