### ISSUE TITLE
This API is using a deprecated version of Swagger

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [ruby-grape/grape-swagger-rails#49]
After updating grape-swagger to 20.1 version swagger won't load documentation. When I have opened Javascript console, it shows error messages:

     This API is using a deprecated version of Swagger!  Please see http://github.com/wordnik/swagger-core/wiki for more info
    Uncaught TypeError: Cannot read property 'length' of undefined swagger-ui.min.self-bfe16e3….js?body=1:217

**Comment by dblock** [comment]
I am not sure what it takes to fix this, please contribute.

**Comment by aschuster3** [comment]
@SuperMasterBlasterLaser check now to see if that error persists

**Comment by SuperMasterBlasterLaser** [comment]
@aschuster3  The problem is solved. I'm closing this issue.
