### ISSUE TITLE
Swagger options not serialized correctly in view

### ISSUE THREAD

**Issue by nevinera** [ruby-grape/grape-swagger-rails#50]
The view file includes options for swagger via

`<html data-swagger-options="<%= GrapeSwaggerRails.options.marshal_dump.to_json %>">`

but that is not html_safe, so the contents of the json string get escaped - we end up with `&quot;` inside our json object.

I'm not sure if this is specific to rails 4, but I made it work properly locally by changing the above to

`<html data-swagger-options='<%== GrapeSwaggerRails.options.marshal_dump.to_json %>'>`

**Comment by dblock** [comment]
Makes sense. If you write a spec I'd love a PR for this.

**Comment by nevinera** [comment]
PR is at #51

**Comment by nevinera** [comment]
The escaped data gets handled by jquery anyway (it de-escapes html entities when processing the data attributes).
