### ISSUE TITLE
problems with request URL

### ISSUE THREAD

**Issue by mgbeyer** [ruby-grape/grape-swagger-rails#54]
Dear develeoper(s),

I have a server with multiple rails apps, each one deployed with a subURI scheme (like "www.lorem.ipsum/app_name/").
I configured your gem so the UI comes up with the following URL"http://www.lorem.ipsum/dbkzakat/takearest/apidoc" -> mount GrapeSwaggerRails::Engine, at: "/takearest/apidoc"

At the bottom of the screen a valid URL ist shown: [ base url: http://www.lorem.ipsum/dbkzakat/takearest/swagger_doc , api version: v1 ]
On top of the screen, also a valid URL shows up: http://www.lorem.ipsum/dbkzakat/takearest/swagger_doc

This works fine so far, now for the problem :)
When I play around with the parameters and if I submit via the "Try it out!" button, a mangled URL is generated which won't work in my case: 

http://www.lorem.ipsum:80/takearest/v1/search/label/any?q=politik&qt=contains&lang=de

As you can see, the subURI part "dbkzakat" is missing! The REST service is perfectly fine, it works, if you alter the URL so it will contain the subURI part.

To clarify, I added a screenshot :)

What's wrong here? Could you please have a look at it?

![fireshot screen capture 024](https://cloud.githubusercontent.com/assets/12907895/15216781/d3867b18-1858-11e6-91a9-c6b091a77d0b.png)

**Comment by dblock** [comment]
I think you'll have better luck with [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions. I'll close this.

**Comment by mgbeyer** [comment]
Why did you close this? My question ist not related to grape itself. Grape works fine. It's a problem with your gem and they way the swagger UI builds the request UI as stated in my ticket above. It's a bug I guess, so could you please help and at least try to have a look at it?

**Comment by dblock** [comment]
Sorry I didn't realize this was a potential bug, so I'll reopen. I'll take a look when/if I have time.

**Comment by mgbeyer** [comment]
Thanks. Maybe my description was a little lengthy to see the point at first glance but I wanted to provide a bit information :)

**Comment by dblock** [comment]
This library cannot guess where the API is located, but you can tell it, either globally, via `GrapeSwaggerRails.options.app_url = '/dbkzakat'` or dynamically with 

```ruby
GrapeSwaggerRails.options.before_filter_proc = proc {
  GrapeSwaggerRails.options.app_url = request.protocol + request.host_with_port + '/dbkzakat'
}
```

Lets us know if that works?

**Comment by mgbeyer** [comment]
Hi,

thanks for the fast reply!

I tried both ways, but neither worked :-(
I put the configuration in "config/initializers/swagger.rb" and it should work there, because I checked your suggestion above with a nonsense path (GrapeSwaggerRails.options.app_url = '/debug'), see screenshot.

So at least partly my config is acknowledged. But the part the "try it out!" button relies on (some JQuery?) seems to have its very own idea of my URL :)

Do you have any other suggestions?

![fireshot screen capture 025](https://cloud.githubusercontent.com/assets/12907895/15314960/2347a0f4-1c15-11e6-8bdd-8511f3e0df59.png)

**Comment by dblock** [comment]
I think you should bring up a very simple app that demonstrates this. Maybe modify https://github.com/ruby-grape/grape-on-rails?

**Comment by mgbeyer** [comment]
Hi,

I don't have really time for that. But I think if you just could have a look at the JavaScript/JQuery stuff inside your gem, it might become clear for the developer. I would do this myself, but all that stuff is minified and thus can't be explored :-(

As far as I can guess, it all seems to boil down to parts of the JQuery stuff not having the proper base path set. Look at the big red X's on the screenshot. "basePath" at the 2nd X is missing the subURI part "dbkzakat".

![unbenannt](https://cloud.githubusercontent.com/assets/12907895/15356368/83294368-1cf8-11e6-8e33-65da8a103017.png)

**Comment by mgbeyer** [comment]
PS: I suspect the following JS, which as I said unfortunately is minified: app/assets/javascripts/grape_swagger_rails/swagger-ui.min.js

**Comment by dblock** [comment]
If you or whomever has time to debug this, the sample project here runs unminified code in development, see https://github.com/ruby-grape/grape-swagger-rails/blob/master/CONTRIBUTING.md#write-code for how to run it.

**Comment by aschuster3** [comment]
@mgbeyer  If possible, could you post your `swagger.rb` initializer?  You can change the root url to lorem.ipsum, but leave the other URI components.  Also, can we see what you pass for the `add_swagger_documentation` method?  Both of these can help us diagnose your problem better.

**Comment by mgbeyer** [comment]
@aschuster3 sure, here we go:

`config/initializers/swagger.rb` :

```
GrapeSwaggerRails.options.url      = "/takearest/swagger_doc"
GrapeSwaggerRails.options.app_url  = Rails.env == "production" ? "/"+Iqvoc.instance_id.downcase : ""   # subURI
GrapeSwaggerRails.options.app_name = Rails.env == "production" ?  Iqvoc.instance_id+" REST" : 'iQvoc REST'
```

`add_swagger_documentation` :

```
module Takearest
  module V1
    class Base < Grape::API
      mount Takearest::V1::Finder
      add_swagger_documentation api_version: 'v1'
      add_swagger_documentation hide_documentation_path: true
      add_swagger_documentation hide_format: true
    end
  end
end
```

**Comment by mgbeyer** [comment]
@dblock 

You mean the sample app in the "spec/dummy" folder right?
I can't get this to start properly, maybe because I develop under a Windows environment (my bundle install throws lots of errors). 
But the JS file in question is not there anyway, or did I miss something? It's just not there, neither under "assets/javascripts" nor "vendor/assets/javascripts" :-/

Bottom line is: I can't run this here locally and I do not want to mess with my staging or production machines (Ubuntu), because I can't tell what bundler exactly will do here and I don't want to risk anything going south on those machines.

Maybe if you could just post a non-minified version of "swagger-ui.js" and I'll have a look at it. With a bit of luck this might help already, some bugs are pretty obvious :)

**Comment by dblock** [comment]
Yes @mgbeyer I mean that project. Can't help much on Windows :(

The source of the minified version is in https://github.com/swagger-api/swagger-ui.

**Comment by mgbeyer** [comment]
Could you please tell me, which exact version of the project above was used in grape-swagger-rails 0.1.0? Then I could fetch the appropriate JS file from swagger-ui project, used in the old version of "grape-swagger-rails" I run here. You know, I've tried to update the whole shebang, but I can't without running into other issues (JavaScript error: This API is using a deprecated version of Swagger!  Please see http://github.com/wordnik/swagger-core/wiki for more info). The URL is not very helpful, I just don't know what to do here? If I can't have a proper update of everything maybe I don't need one at all. I could try and just find the bug in the "legacy" JS file, fix it, minify and re-compile my assets with this fixed version. Maybe just a hack will do :)

**Comment by dblock** [comment]
First, 0.1.0 is a year old, so I am not sure why you're trying to use that. I would focus on getting master to run on your dev environment (get a VirtualBox with linux?).

You'll have to look at commits against the 0.1.0 tag, https://github.com/ruby-grape/grape-swagger-rails/tree/v0.1.0, to find out which version of the JS was used there. Looks like it was [September 2014](https://github.com/ruby-grape/grape-swagger-rails/commit/9ac2bfda5649b9d552c2d986a9ea697a5aa221e3).

**Comment by mgbeyer** [comment]
I know, I know :)
But I've already tried to update a couple days ago, and as I said, I run into different probleme in the form of this JavaScript error:

```
This API is using a deprecated version of Swagger! Please see http://github.com/wordnik/swagger-core/wiki for more info
```

I'm completely stuck here :-/

**Comment by dblock** [comment]
This is https://github.com/ruby-grape/grape-swagger-rails/issues/49.

**Comment by mgbeyer** [comment]
Thanks, didn't know this one. So the issue is solved by #49 I guess and I'll give the update another try. I'm closing this.

**Comment by pieterocp** [comment]
Did that actually fix the underlying issue?

**Comment by pieterocp** [comment]
Well, I had a similar issue but it turned out to be a misconfiguration of the `base_path` variable, e.g. was `base_path: ->(request) { "#{request.base_url}/api" },` when it should have been `base_path: '/api',`
