### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'definitions' of null

### ISSUE THREAD

**Issue by abhilashak** [ruby-grape/grape-swagger-rails#58]
Hi authors,

 I followed the 'grape-swagger-rails' documentation and I am getting the /swagger_doc.json initial page  loads fine from swagger ui as follows:

<img width="1396" alt="swagger-first-page-ok" src="https://cloud.githubusercontent.com/assets/381856/16072957/44843360-3301-11e6-94bf-7d409225bb45.png">

But apart from this page all other requests, I am getting one of 2 errors

**1st Error:** Unable to Load SwaggerUI
(I am testing '401 Unauthorised' page works or not with swagger documentation)

For this response Swagger ui is not loading and showing the following error:
Unable to Load SwaggerUI
apidoc:50 401 :  http://g_m.lvh.me:3000/content/api/v1/activities/23

<img width="1398" alt="swagger-401-unauthorised" src="https://cloud.githubusercontent.com/assets/381856/16072968/4d7a8eb0-3301-11e6-8a55-8621429c5d15.png">

**2nd Error:** Uncaught TypeError: Cannot read property 'definitions' of null

(I am testing  '200 Created' page works or not with swagger documentation)
For all other successful requests (200) where I am sending json response back, occurs the following error:
 _Uncaught TypeError: Cannot read property 'definitions' of null_

<img width="1395" alt="screen shot 2016-06-15 at 1 57 54 pm" src="https://cloud.githubusercontent.com/assets/381856/16072983/5a08bac6-3301-11e6-835d-fa754e35241a.png">

<img width="1395" alt="screen shot 2016-06-15 at 1 58 10 pm" src="https://cloud.githubusercontent.com/assets/381856/16072982/59ec66a0-3301-11e6-9761-8f5db8c4909f.png">

**NOTE:** I implemented this on a Rails Engine that is mounted on '/content'

I tried a lot, feeling that any configuration I missed to include all these urls in swagger ui. But nothing I can found. Reply me if you have a solution for this else please fix this issue as soon as possible.

**Comment by dblock** [comment]
It looks like your API requires authentication. What happens if you just go to /content/api/v1/activities in a browser?

**Comment by abhilashak** [comment]
@dblock No, I commented all authentication and autorization part and started to test. In browser the path /content/api/v1/activities gives all activities json.I am testing it in postman. And it also gives json response back when simply accessing '/content/api/v1/activities'.

**Comment by dblock** [comment]
Well, the API responds with a 401, examine the network tab and see why. Could be CORS or something like that.

**Comment by abhilashak** [comment]
:) I think you are misunderstood because of I mentioned 1st Error: 401 Unauthorised, Actually I meant I was testing this '401 Unauthorised' functionality in the 2nd case (here I am not commented the authentication). It works well. 401 is my expected answer. But in this case also Swagger shows Unable to load Swagger ui. Atleast I am expecting some ui from swagger in 401 page also.

And the real bug comes in the my 3rd test, where I commented the authentication and tested the response. Server sending the json response back and swagger shows some javascript error in console. Why that? '/content/api/v1/activities' url cannot found by swagger?

**Comment by aschuster3** [comment]
That bar at the top is NOT to test your API endpoints.  It is to put the JSON endpoint of your valid OpenAPI v2.  When you put a URL in that bar, Swagger UI tries to build the API calls and if the endpoint doesn't return JSON, it errors out.

As you add your API calls to grape (which I assume you're using) and document them using grape-swagger, they will automatically begin populating on your documentation page as long as you're pointing to you JSON endpoint.  [Eventually your API will look like this and you'll be able to interact with it on the page](http://petstore.swagger.io/).

**Comment by abhilashak** [comment]
@aschuster3  Great. I totally misunderstood this may be. Now I got the idea. Thank you. Yes I am using Grape. Here I used [grape-swagger-rails](https://github.com/ruby-grape/grape-swagger-rails/). 

<img width="1087" alt="screen shot 2016-06-15 at 8 30 17 pm" src="https://cloud.githubusercontent.com/assets/381856/16084991/418ea08c-3338-11e6-8e84-73794d3212e1.png">

<img width="798" alt="screen shot 2016-06-15 at 8 28 34 pm" src="https://cloud.githubusercontent.com/assets/381856/16084992/4194a91e-3338-11e6-86d0-359a37cc2521.png">

My doubt is how to generate this 'Valid OpenAPI v2 JSON endpoint' to give in that top bar? Is that already generated by grae-swagger when I add 'add_swagger_documentation' in screenshot no. 2 ?

**Comment by dblock** [comment]
Ah thanks @aschuster3 I see what's happening here ;) 

@abhilashak the documentation endpoint should be /api/v1/swagger_doc I believe.

**Comment by abhilashak** [comment]
@dblock No, I given the path 'api/v1/swagger_doc' but it not works. It shows the same error: 'Unable to Load SwaggerUI'.  I think 'content/swagger_doc.json' is the JSON Endpoint as @aschuster3 specified, as it works well without any issue (see screenshot no.1).  But it not showing my Grape API calls. Just showing 

    BASE URL: /content
    API VERSION: 0.0.1

**Comment by aschuster3** [comment]
Yep, grape-swagger auto-generates the Valid OpenAPI v2 JSON endpoint.  You should be able to check that the behavior is correct by visiting `[your_url]/swagger_doc.json` based on the defaults that grape-swagger has.  [Here's what the pet store example's JSON looks like for reference](http://petstore.swagger.io/v2/swagger.json).

You can take a look over at [grape-swagger's instructions for configuring](https://github.com/ruby-grape/grape-swagger#configure) to know what the default behavior is.  By looking at your first picture in your original question, it appears that you are navigating to the correct path for the JSON.  

After verifying all of that, the problem *might* be arising from how you're mounting your APIs.  `add_swagger_documentation` should be the LAST thing that you call.  So your file should look as follows:

```ruby
require 'grape-swagger'

module ContentManager
  class API < Grape::API
    
    # All of your mount statements and logic
    
    add_swagger_documentation(hide_documentation_path: true)
```

I think that should solve your problem!

**Comment by abhilashak** [comment]
@aschuster3 Wahhh Super great ...Thank you so much 💯  That was the issue!! 

When I was adding the method 'add_swagger_documentation' I just thought It will fetch all the API calls mentioned in that API class. But we are mounting the calls later. So the method cannot find the APIs! May be I confused the mount stuff with something like load/include. 

I just added the method above, just for nice code!

Guys finally it looks like this:

<img width="1395" alt="screen shot 2016-06-15 at 11 18 29 pm" src="https://cloud.githubusercontent.com/assets/381856/16091267/85396d0e-3350-11e6-9d23-34e21e523948.png">

Thank you, 👍

**Comment by aschuster3** [comment]
Great!  I'm gonna go ahead and close this issue.

Glad I could help!

**Comment by dblock** [comment]
Excellent detective work @aschuster3!
