### ISSUE TITLE
Pre-fill some inputs

### ISSUE THREAD

**Issue by theonegri** [ruby-grape/grape-swagger-rails#59]
I have some inputs that I'd like to pre-fill when a user is logged in like the user's CLIENT_TOEKN.
![screenshot 2016-06-29 11 46 37](https://cloud.githubusercontent.com/assets/1821498/16464633/f189ba8c-3def-11e6-9e91-3d89cda9f7cc.png)

But I can't figure out how to do it.

**Comment by aschuster3** [comment]
Could you please post what you can of your `swagger.rb` initializer?  

Also, did you take a look at [this part of the documentation covering tokens like this](https://github.com/ruby-grape/grape-swagger-rails#basic-authentication)?  Was there a part of that which did not cover your use case?  You could auto-fill the token at the top of the page so that users don't have to input it at the individual call level.

**Comment by theonegri** [comment]
@aschuster3 
swagger.rb
```
GrapeSwaggerRails.options.url      = '/api/1/swagger_doc'
GrapeSwaggerRails.options.app_url  = GetEnv.fetch('APP_URL')
GrapeSwaggerRails.options.app_name = 'My API Documentation'
GrapeSwaggerRails.options.api_key_name = 'CLIENT_TOKEN'
GrapeSwaggerRails.options.api_key_type = 'query'
GrapeSwaggerRails.options.before_filter do |request|
  GrapeSwaggerRails.options.api_key_default_value = 'test_token'
end
```

I don't actually want to auto-fill the token at the top of the page. I think it's counter intuitive for users and i'm confident they won't notice it.

**Comment by aschuster3** [comment]
That's all good, unfortunately this gem doesn't provide easy means to drop default values as it should ideally be handled in the `grape-swagger` gem.  

Off the top of my head, the two options I can come up with are to use default values as defined by the Open API spec [and following the rules from `grape-swagger`](https://github.com/ruby-grape/grape-swagger#setting-a-swagger-defaultvalue), or you can find a means to inject by adding a JavaScript file that fetches the token and finds the locations to insert it via the DOM manually.  Do either of those seem like plausible solutions?

**Comment by theonegri** [comment]
@aschuster3 The first option makes sense. Thanks!
