### ISSUE TITLE
Exclude grape and grape-swagger from deps

### ISSUE THREAD

**Issue by swistaczek** [ruby-grape/grape-swagger-rails#60]
Hello,
Please exclude **grape** and **grape-swagger** from gem dependencies. Main reason for this usage of **grape-swagger-rails** only as swagger-ui without code that depends on grape or/and grape-swagger.

**Comment by dblock** [comment]
What stops working when we remove those dependencies? Can you please PR it?

**Comment by aschuster3** [comment]
@swistaczek This is now live in master and will be released sometime soon.  Thank you for your recommendation!
