### ISSUE TITLE
How to prefill API key for swagger UI

### ISSUE THREAD

**Issue by nhinze** [ruby-grape/grape-swagger-rails#64]
I'm using:
 - Rails 4.2.6
 - Grape, Win Bouncer, Doorkeeper

How can I pre-fill API key for logged in user for swagger UI? The only way I figured out how to get the current token is by creating on separate rails app as an OauthClient. However, for convenience and in production I would like to prefill the api key in swagger UI. Or how can a logged in user get the api key easily?

**wine_bouncer.rb:**

```
WineBouncer.configure do |config|
  config.auth_strategy = :swagger

  config.define_resource_owner do
    User.find(doorkeeper_access_token.resource_owner_id) if doorkeeper_access_token
  end
end
```

**swagger.rb:**

```
GrapeSwaggerRails.options.url      = '/api/mobile/swagger_doc.json'
GrapeSwaggerRails.options.app_url  = 'https://www.domain.com'
GrapeSwaggerRails.options.api_key_name = 'access_token'
GrapeSwaggerRails.options.api_key_type = 'query'
```

**Comment by aschuster3** [comment]
Hey @nhinze,

[Does this part of the README not solve your problem?](https://github.com/ruby-grape/grape-swagger-rails#pre-fill-authentication)

**Comment by aschuster3** [comment]
Totally understandable!

As a basic understanding, you can treat the inside of this `before_filter` similarly to how you would treat a `before_filter` inside of a Rails controller, meaning it has access to a lot of useful things, the most important being the current session (if one exists).  If you are using Doorkeeper, you have access to a function called `current_user`, which will return a User instance tied to the existing session.  I'm not sure about your OAuth2 config, but basically you should be able to do something as below:

```ruby
GrapeSwaggerRails.options.before_filter do |request|
  user = current_user

  # I've made this function up, but once you have access to the user, 
  # you can basically get any tokens related to it that you would need.
  key = user.get_oauth_key


  GrapeSwaggerRails.options.api_key_default_value = key
end
```

**Comment by nhinze** [comment]
Thanks, it got me in the right direction:

```
GrapeSwaggerRails.options.before_filter do |request|
  GrapeSwaggerRails.options.api_key_default_value = current_user.token.token
end
```

In user.rb model add:

`has_one :token, -> { order 'created_at DESC' }, class_name: Doorkeeper::AccessToken, foreign_key: :resource_owner_id`

Credit: http://stackoverflow.com/questions/24206483/how-to-return-doorkeeper-access-token-as-json

**Comment by aschuster3** [comment]
Great, glad I could help.  Would you consider this issue resolved?  If so, feel free to mark it as such.

**Comment by dblock** [comment]
I'd love this in the README, under something like "integration with doorkeeper", @nhinze would you like to contribute?

**Comment by nhinze** [comment]
I created a pull request to update the README.

**Comment by dblock** [comment]
Thanks @nhinze
