### ISSUE TITLE
How do I change heading in swagger?

### ISSUE THREAD

**Issue by lakshmivrv** [ruby-grape/grape-swagger-rails#66]
How do I change heading in swagger

In swagger UI all the headings are having default messages like "user: Operations about user". Is there any way that I can customize the heading?

![swagger_heading](https://cloud.githubusercontent.com/assets/10494545/17437136/75bdc990-5b39-11e6-978e-f202bd00f610.png)

**Comment by aschuster3** [comment]
Hey @lakshmivrv,

If you want to have a custom header, it's actually related to the `grape-swagger` gem.  Using your examples, to add a custom header to your code in your API file would look something like this:

```ruby
namespace :decoder, desc: 'This is my custom header for decoder' do 
    # Your API logic
end
```

Let me know if you have any issues!

**Comment by swistaczek** [comment]
Hey, is key ```:desc``` still valid for namespace? I am using ```grape-swagger (0.30.1)``` and I found out that adding ```:desc``` key does not change output for namespace description (for example: ```Operations about products```.

**Comment by aschuster3** [comment]
Unfortunately it might not be.  `grape-swagger-rails` has a list of compatible versions on the README  [found here](https://github.com/ruby-grape/grape-swagger-rails#compatibility) and we haven't yet tested with `0.30.1`.

**Comment by Zlatov** [comment]
Adding the `tags: ...` option worked for me. Described in the [documentation#tags-](https://github.com/ruby-grape/grape-swagger/#tags-). 

The tag name must match the namespace.

```rb
add_swagger_documentation \
  ...
  tags: [
    {name: 'products', description: 'A description of namespace'}
  ]
```

It's a little awkward that we can't set a `desc` before namespace/resources, `desc` probably has its own sugar and therefore only applies to get/post...
