### ISSUE TITLE
URI::InvalidURIError in GrapeSwaggerRails::Application#index

### ISSUE THREAD

**Issue by RathanakSreang** [ruby-grape/grape-swagger-rails#69]
Currently, I  face a problem when I try to access `http://localhost:3000/swagger` and it raise error 
URI::InvalidURIError in GrapeSwaggerRails::Application#index
bad URI(is not URI?): file-digest:///home/../app/assets/config/grape_swagger_rails
Does anyone know how to fix this issue?

**Comment by aschuster3** [comment]
Hey @RathanakSreang, please post your initializer, the relevant parts of your `routes.rb`, and the file where you call the function `add_swagger_documentation`

**Comment by RathanakSreang** [comment]
@aschuster3 

Here my code:
```
#app/controller/api/v1/base.rb
require "grape-swagger"

module API
  module V1
    class Base < Grape::API
      mount API::V1::Users

      add_swagger_documentation(
        api_version: "v1",
        hide_documentation_path: true,
        mount_path: "/api/v1/swagger_doc",
        hide_format: true
      )
    end
  end
end
```
```
#config/initializers/swagger.rb
GrapeSwaggerRails.options.before_filter_proc = proc {
  if Rails.env.test? || Rails.env.development?
    base_url = request.protocol + request.host_with_port
  else
    base_url = Settings.api.base_url[Rails.env]
  end

  GrapeSwaggerRails.options.app_url = "#{base_url}/api/#{Settings.api.current_version}"
  GrapeSwaggerRails.options.app_name = Settings.api.name
}

```
```
 #config/routes.rb
  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine, at: "/swagger"
```

**Comment by aschuster3** [comment]
So, I spun up an instance to see if could reproduce on this information alone and I was unable.  Could you post the full Error message?

**Comment by RathanakSreang** [comment]
Hi @aschuster3 
I found solution which I need to update my ruby version to 2.2.3

**Comment by aschuster3** [comment]
Thanks for letting me know, sorry I couldn't be of more help, haha

I'm going to go ahead and close this, if you need any more help, feel free to open another Issue
