### ISSUE TITLE
Setting API key default value doesn't work immediately

### ISSUE THREAD

**Issue by konto-andrzeja** [ruby-grape/grape-swagger-rails#79]
Hello, I'm using [this method](https://github.com/ruby-grape/grape-swagger-rails#integration-with-doorkeeper) to set API key default value:
```
GrapeSwaggerRails.options.before_action do |request|
  GrapeSwaggerRails.options.api_key_default_value = some_key
end
```
It fills the input, but it doesn't send the key. To force it to do so I need too trigger js `change` event on the input, e.g. add space, press enter, remove space, press enter again.

In the source code it looks like the only thing `api_key_default_value` does is [setting the initial value of the input](https://github.com/ruby-grape/grape-swagger-rails/blob/master/app/views/grape_swagger_rails/application/index.html.erb#L85). It doesn't trigger [change event](https://github.com/ruby-grape/grape-swagger-rails/blob/master/app/views/grape_swagger_rails/application/index.html.erb#L57) that would actually update the key that is used.

Is it a bug or am I doing something wrong here? If it's a bug, I can prepare PR to fix it.

**Comment by aschuster3** [comment]
Interesting, this may have come about as part of the last update to the `swagger` dependency.  We absolutely welcome a PR to fix the issue.

**Comment by konto-andrzeja** [comment]
For now I used the following code to solve the issue:
```
GrapeSwaggerRails.options.hide_api_key_input = true
GrapeSwaggerRails.options.before_action do |request|
  GrapeSwaggerRails.options.app_url = "#{request.protocol}#{request.host_with_port}"
  GrapeSwaggerRails.options.headers['Authorization'] = "Bearer #{current_user&.token&.token}"
end
```
I still intend to fix this, but I don't know when I'll be able to find time.
