### ISSUE TITLE
Does this gem integrate with https://github.com/kendrikat/grape-swagger-ui ?

### ISSUE THREAD

**Issue by pablocrivella** [ruby-grape/grape-swagger-rails#9]

**Comment by aschuster3** [comment]
Better late than never:

It appears `grape-swagger-ui` is a different attempt at integrating `grape` and `grape-swagger` into a Rail project.  It also appears as though `grape-swagger-ui` hasn't been updated in a year and is currently only known to support Rails 3 based on it's README.  

Nothing in `grape-swagger-rails` is written with the intent of being integrated with `grape-swagger-ui` to my knowledge.  If you had both gems active in a project, there may be unexpected collisions in logic.
