### ISSUE TITLE
assets issue in rails 6

### ISSUE THREAD

**Issue by Faisal-nfl** [ruby-grape/grape-swagger-rails#96]
with rails 6, lot of things changed but not sure what I have to do,
 it gives error

> Asset `grape_swagger_rails/application.css` was not declared to be precompiled in production.
> Declare links to your assets in `app/assets/config/manifest.js`.
> 
>   //= link grape_swagger_rails/application.css
> and restart your server

I did this but same issue, not sure what else I have to do

**Comment by dblock** [comment]
This shouldn't be a problem. Somehow you're including the CSS/JS uncompressed from a subfolder instead of whatever the default inclusion happens with Railtie.

- make a vanilla Rails 6 project with this gem, it should work clean
- put up your project on github and we can try to help you

**Comment by Faisal-nfl** [comment]
@dblock 
thanks for response
I created a sample project on github
[rails6_backend](https://github.com/Faisal-nfl/rails6_backend)

its giving same error, have a look please.
(swagger stuff is in the last commit)

**Comment by Faisal-nfl** [comment]
@dblock can you clarify that why its giving assets issue ?

**Comment by Faisal-nfl** [comment]
For another project faced very same issue even after adding those lines in `menifest.js`
after trying different stuff for hours it started to work by addling these lines at top of  `app/assets/config/manifest.js`, its looks like this now

```
//= link grape_swagger_rails/application.css
//= link grape_swagger_rails/application.js
//= link_tree ../images
//= link_directory ../stylesheets .css

```

**Comment by dblock** [comment]
Looking at https://github.com/Faisal-nfl/rails6_backend/blob/master/app/assets/config/manifest.js it's pretty custom and doesn't include dependencies with `require_tree .`. I think your solution is a good one. I'd appreciate a better explanation for the README in the https://github.com/ruby-grape/grape-swagger-rails#enabling-in-a-rails-api-project section. Want to contribute?

**Comment by Faisal-nfl** [comment]
sure, I would love to.
though I never contributed to such project.
what I have to do 
1- fork 
2- clone 
3- make changes 
4- generate pull request

or anything else?

**Comment by Faisal-nfl** [comment]
@dblock 
I tried to explain it and generated pull request.
have a look if ok? [pull request](https://github.com/ruby-grape/grape-swagger-rails/pull/97)
